Solver autobounds failed with error: Command '['venv_autobounds/bin/python3', 'src/solvers/autobounds_solver.py', '--common_data', 'data/shared/common_data.json', '--common_data', 'data/shared/common_data.json']' returned non-zero exit status 1.
